### ISSUE TITLE
Dist folder is blank

### ISSUE THREAD

**Issue by Ardakilic** [ritz078/socialShare.js#1]
Hello,

Firstly, thank you for your hard work!

It's not a big deal, but javascripts in dist folder are blank. Also the source has a line that logs data to console.

I'd appreciate if you could check this.

Thanks,

**Comment by ritz078** [comment]
Thanks for informing. Its fixed now . :smile: I am closing this issue.

**Comment by Ardakilic** [comment]
Aha, you are super fast! thank you @ritz078 :smile: :+1:

**Comment by Ardakilic** [comment]
@ritz078 One more request: If possible, could you please add as a new tag? I'll be installing from npm, and it downloads the old tag instead of this.

**Comment by ritz078** [comment]
Check now :)

**Comment by Ardakilic** [comment]
@ritz078 You sir, are a life saver, thank you so much! :clap:
