### ISSUE TITLE
[Request] An option to bypass the fetch for sharing counter

### ISSUE THREAD

**Issue by Ardakilic** [ritz078/socialShare.js#2]
Hello,

On each request, regardless of the usage of counts, the script goes to https://count.donreach.com to fetch share counts.

I won't be using the counts, so I'd appreciate if there would be an option to bypass this.

Thanks in advance,

**Comment by ritz078** [comment]
done. set `counts` to false

**Comment by Ardakilic** [comment]
Thank you so much, will check this right away! :dancer: 

Edit: Yup, works as a treat, thanks!
