### ISSUE TITLE
IE9 (and I'm guessing IE8) throws Invalid Argument on window.open

### ISSUE THREAD

**Issue by cauli** [ritz078/socialShare.js#4]
```
SCRIPT87: Invalid argument.
jquery.socialshare.min.js, line 3 character 1837
```

May be related: Hyphens on new window name

> http://stackoverflow.com/questions/9590282/script87-invalid-argument-in-ie-9-asp-net-c-sharp

Also may fix: Wrapping window.open() in parenthesis

> http://stackoverflow.com/questions/710756/ie8-var-w-window-open-message-invalid-argument

**Comment by cauli** [comment]
Removing hyphens from new window name worked for me.

**Comment by ritz078** [comment]
would you like to send a PR ? :)

**Comment by cauli** [comment]
I think first you would need to decide whether you prefer to browser-sniff IE browsers and then remove the hyphens (and spaces) for these browsers, or if you would prefer to remove these characters for all browsers.

Sadly I half-heartedly changed the minified file directly as I was reaching a deadline, I can't make a PR  right now :(.
